
const FacultyDatass = [
    {
        id: 1,
        SrNo: "1",
        Image: "1",
        Name: "Dr. D. N. Rewadkar",
        Gender: "Male",
        Qualification: "M.Tech (CSE) B.E(IT)",
        Mobile: "9960465169",
        Email: "priyanka.kamdi@gmail.com",
        MoreInfo: "https://drive.google.com/file/d/1wW9EtYi5b7dCDiB8sb4nILJjovM2jFUL/view",
    },
    {
        id: 2,
        SrNo: "2",
        Image: "1",
        Name: "Mrs. P. S. Ghode",
        Gender: "Female",
        Qualification: "M.Tech (CSE) B.E(IT)",
        Mobile: "9960465169",
        Email: "priyanka.kamdi@gmail.com",
        MoreInfo: "https://drive.google.com/file/d/1wW9EtYi5b7dCDiB8sb4nILJjovM2jFUL/view",
    },
    {
        id: 3,
        SrNo: "3",
        Image: "1",
        Name: "Mrs. S. D. Raut",
        Gender: "Female",
        Qualification: "M.E(CN) B.E(IT)",
        Mobile: "9975033924",
        Email: "sneha.raut320@gmail.com",
        MoreInfo: "https://drive.google.com/file/d/1S4Xcgb9IPsjc_5IoeB3lPcBkHOBHdcAU/view",
    },
    {
        id: 4,
        SrNo: "4",
        Image: "1",
        Name: "Miss. P. C. Fafat",
        Gender: "Female",
        Qualification: "M.E(IT), BE(CSE)",
        Mobile: "8087160142",
        Email: "poonamfafat@gmail.com",
        MoreInfo: "https://drive.google.com/file/d/16t3QSIureVPpp2cjahb41S920ZIBW7Du/view",
    },
    {
        id: 5,
        SrNo: "5",
        Image: "1",
        Name: "Ms. S. S. Sutar",
        Gender: "Female",
        Qualification: "BE(IT), M.E(CS)",
        Mobile: "8149741170",
        Email: "sheetalsutar13@gmail.com",
        MoreInfo: "https://drive.google.com/file/d/1PRpHEex6u_FI55W1v4yzKIfBFCg__MSm/view",
    },
    {
        id: 6,
        SrNo: "6",
        Image: "1",
        Name: "Ms. J. G. Dabhade",
        Gender: "Female",
        Qualification: "BE(IT), M.E(Comp.Engg)",
        Mobile: "9730965316",
        Email: "jyot.da29@gmail.com",
        MoreInfo: "https://drive.google.com/file/d/1-QM4MfVlCoK-iWWY33ZaSW14VWg9fuXB/view",
    },
    {
        id: 7,
        SrNo: "7",
        Image: "1",
        Name: "Mr. Y. U. Bodhe",
        Gender: "Male",
        Qualification: "BE(Comp.Engg), M.Tech(Comp.Sci.& Engg.)",
        Mobile: "8530407444",
        Email: "bodheyog@gmail.com",
        MoreInfo: "https://drive.google.com/file/d/1ee4mxYHdLDZ9HrIqnToEIw70xooupqlF/view",
    }

]

export default FacultyDatass;